config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  resources :articles do
    resources :comments, only: [:create, :destroy]

    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

   attachment :image

   validates :title, presence: true
   validates :category, presence: true
   validates :body, presence: true, length: { maximum: 200 }

   belongs_to :user
   has_many :comments, dependent: :destroy
   has_many :favorites, dependent: :destroy

   def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
   end

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]

  before_action :configure_permited_parameters, if: :devise_controller?

 def after_sign_in_path_for(resouce)
   articles_path
 end

 def after_sign_up_path_for(resouce)
   articles_path
 end

  protected

  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_image])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.page(params[:page]).reverse_order
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :category, :image, :body)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    comment = current_user.comments.new(comment_params)
    comment.article_id = @article.id
    comment.save
    redirect_to article_path(@article)
  end

  def destroy
    Comment.find_by(id: params[:id], article_id: params[:article_id]).destroy
    redirect_to articles_path
  end


  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    favorite = current_user.favorites.new(article_id: @article.id)
    favorite.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    favorite = current_user.favorites.find_by(article_id: @article.id)
    favorite.destroy
    redirect_to article_path(@article)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.all
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:profile_image, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class ="col-md-3"></div>
    <div class ="col-md-8 offset-md-1">
      <h1>Edit Article</h1>
      <% if @article.errors.any? %>
        <%= @article.errors.count %>件のエラーが発生しました<br />
        <% @article.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
      <% end %>
      <%= form_with model:@article, local:true do |f| %>
      <div class = "form">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>

      <div class = "form">
        <%= f.label :category %><br />
        <%= f.text_field :category %>
      </div>

      <div class = "form">
        <%= f.label :image %><br />
        <%= f.attachment_field :image %>
      </div>

      <div class = "form">
        <%= f.label :body %><br />
        <%= f.text_area :body %>
      </div>

      <%= f.submit '投稿編集' %>

    <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class = "container" >
  <div class = "row" >
    <div class = "col-md-3" style = "background-color: green;">
      <h1>テスト</h1>
      <h2></h2>

    </div>
    <div class = "col-md-8 offset-md-1" style = "background-color: blue;">
      <h2>記事一覧</h2>

      <table>
        <thead>
          <tr>
            <th>category</th>
            <th></th>
            <th>title</th>
            <th>body</th>
            <th>writer</th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
          <tr>
            <td><%= article.category %></td>
            <td><%= attachment_image_tag article, :image, :fill, 60, 60 %></td>
            <td><%= link_to article.title, article_path(article) %></td>
            <td><%= article.body %></td>
            <td><%= article.user.name %></td>
            <td><%= link_to "#{article.comments.count}コメント", article_path(article.id) %></td>
          </tr>
          <% end %>
          <%= paginate @articles %>
        </tbody>
      </table>
    </div>
  </div>
  <div class = "row">
    <div class = "col-6" style = "background-color: orange;">
      <h3>テスト</h3>
    </div>
    <div class = "col-6" style = "background-color: red;">
      <h4>テスト</h4>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class = "container">
  <div class = "row">

    <div class ="col-md-3"></div>
    <div class ="col-md-8 offset-md-1">
      <% if @article.errors.any? %>
        <%= @article.errors.count %>件のエラーが発生しました<br />
        <% @article.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
      <% end %>
      <h1>New Article</h1>
      <%= form_with model:@article, local:true do |f| %>
      <div class = "form">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>

      <div class = "form">
        <%= f.label :category %><br />
        <%= f.text_field :category %>
      </div>

      <div class = "form">
        <%= f.label :image %><br />
        <%= f.attachment_field :image %>
      </div>

      <div class = "form">
        <%= f.label :body %><br />
        <%= f.text_area :body %>
      </div>

      <%= f.submit '新規投稿' %>

    <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class = "container" >
  <div class = "row" >
    <div class = "col-md-3" style = "background-color: green;"><h1>テスト</h1></div>
    <div class = "col-md-8 offset-md-1" style = "background-color: blue;">
      <h2>記事詳細</h2>
      <table>
        <thead>
          <tr>
            <th>category</th>
            <th></th>
            <th>title</th>
            <th>body</th>
            <th>writer</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @article.category %></td>
            <td><%= attachment_image_tag @article, :image, :fill, 100, 100 %></td>
            <td><%= link_to @article.title, article_path(@article) %></td>
            <td><%= @article.body %></td>
            <td><%= @article.user.name %></td>
            <% if @article.user_id == current_user.id %>
            <td><%= link_to '削除', article_path(@article), method: :delete %> </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class ="comments">
        <p>コメント件数:<%= @article.comments.count %></p>
        <% @article.comments.each do |comment| %>
          <%= comment.user.name %>
          <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>

          <div class ="comment-delete">
            <% if comment.user == current_user %>
            <%= link_to "コメント削除", article_comment_path(@article, comment), method: :delete %>
            <% end %>
          </div>
        <% end %>
        <div class="comment-box">
          <% if @article.favorited_by?(current_user) %>
            <%= link_to article_favorites_path(@article), method: :delete do %>
            ❤️ <%= @article.favorites.count %>いいね
            <% end %>
          <% else %>
            <%= link_to article_favorites_path(@article), method: :post do %>
            ♡<%= @article.favorites.count %>いいね
            <% end %>
          <% end %>
          </div>
          <div class ="new-comments">
        <%=form_with(model:[@article, @comment], local:true) do |f| %>
          <%= f.text_area :comment, row:'5', placeholder:'コメントをここに' %>
          <%= f.submit '送信する' %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class = "row">
    <div class = "col-6" style = "background-color: orange;">
      <h3>テスト</h3>
    </div>
    <div class = "col-6" style = "background-color: red;">
      <h4>テスト</h4>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<div class = "container" >
  <div class = "row" >
    <div class = "col-md-3" style = "background-color: green;">
      <h1>テスト</h1>
      <h2></h2>

    </div>
    <div class = "col-md-8 offset-md-1" style = "background-color: blue;">
      <h2>記事一覧</h2>

      <table>
        <thead>
          <tr>
            <th>category</th>
            <th></th>
            <th>title</th>
            <th>body</th>
            <th>writer</th>
          </tr>
        <tbody>
          <% @articles.each do |article| %>
          <tr>
            <th><%= article.category %></th>
            <th><%= attachment_image_tag article, :image %></th>
            <th><%= link_to article.title, article_path(article) %></th>
            <th><%= article.body %></th>
            <th><%= article.user.name %></th>
            <th><%= link_to "#{article.comments.count}コメント", article_path(article.id) %></th>
          </tr>
          <% end %>
        </tbody>
        </thead>
      </table>
    </div>
  </div>
  <div class = "row">
    <div class = "col-6" style = "background-color: orange;">
      <h3>テスト</h3>
    </div>
    <div class = "col-6" style = "background-color: red;">
      <h4>テスト</h4>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3"></div>

    <div class="col-md-8 ofset-md-1"></div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <h1>HOME</h1>
    <ul>
    <% if user_signed_in? %>
      <li><%= link_to '新規投稿' , new_article_path %></li>
      <li><%= link_to '記事一覧' , articles_path %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <li><%= link_to 'マイページ', user_path(current_user.id) %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path %></li>
      <li><%= link_to 'サインアップ', new_user_registration_path %></li>
    <% end %>
    </ul>
  </header>

  <body>
    <%= yield %>
  </body>

  <footer>
    <h3>Footer</h3>
  </footer>
</html>

app/views/users/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class ="col-md-3"></div>
    <div class ="col-md-8 offset-md-1">
      <h2>プロフィール編集</h2>
      <%= form_with model:@user, local:true do |f| %>
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
        
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg" %>
        
        <label for="inputImage">ProfileImage</label>
        <%= f.attachment_field :profile_image %>
        <%= f.submit "変更を保存" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container" >
  <div class = "row" >
    <div class = "col-md-3" style = "background-color: green;">
      <h1>テスト</h1>
      <h2></h2>
      <p><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></p>
      <% if @user.id == current_user.id %>
        <p><%= link_to 'プロフィール編集', edit_user_path(@user) %></p>
      <% end %>

    </div>
    <div class = "col-md-8 offset-md-1" style = "background-color: blue;">
      <h2>マイページ</h2>

      <table>
        <thead>
          <tr>
            <th>category</th>
            <th></th>
            <th>title</th>
            <th>body</th>
            <th>writer</th>
          </tr>
        <tbody>
           <% @articles.each do |article| %>
          <tr>
            <th><%= article.category %></th>
            <th><%= attachment_image_tag article, :image, :fill, 100, 100 %></th>
            <th><%= link_to article.title, article_path(article) %></th>
            <th><%= article.body %></th>
            <th><%= article.user.name %></th>
            <% if @user == current_user %>
            <th><%= link_to '編集' , edit_article_path(article) %></th>
            <th><%= link_to '削除' , article_path(article), method: :delete %></th>
            <% end %>
          </tr>
          <% end %>
        </tbody>
        </thead>
      </table>
    </div>
  </div>
  <div class = "row">
    <div class = "col-6" style = "background-color: orange;">
      <h3>テスト</h3>
    </div>
    <div class = "col-6" style = "background-color: red;">
      <h4>テスト</h4>
    </div>
  </div>
</div>